import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Textarea } from '@/components/ui/textarea';
import AppLayout from '@/layouts/app-layout';
import { Head, useForm } from '@inertiajs/react';
import React, { useState } from 'react';

// Define the available services the bot can sell
const AVAILABLE_SERVICES = [
    { id: 'airtime', label: 'Airtime Recharge' },
    { id: 'data', label: 'Data Bundles' },
    { id: 'cable', label: 'Cable TV' },
    { id: 'electricity', label: 'Electricity Bills' },
];

interface Props {
    globalBotUsername: string; // e.g. "SpurConnectBot"
    merchantCode: string; // e.g. "biz_12345"
    isActive: boolean;
    welcomeMessage: string | null;
    allowedServices?: string[]; // Array of service IDs, e.g. ['airtime', 'data']
    totalSalesAmount?: number; // Total revenue generated by the bot
    totalSalesCount?: number; // Number of successful transactions
}

export default function MerchantTelegramBot({
    globalBotUsername,
    merchantCode,
    isActive,
    welcomeMessage,
    allowedServices = ['airtime', 'data', 'cable', 'electricity'], // Default fallback
    totalSalesAmount = 0,
    totalSalesCount = 0
}: Props) {
    const [copied, setCopied] = useState(false);

    const { data, setData, put, processing, recentlySuccessful } = useForm({
        is_active: isActive,
        welcome_message: welcomeMessage || '',
        allowed_services: allowedServices,
    });

    const enabledServicesCount = data.allowed_services.length;
    const botLink = `https://t.me/${globalBotUsername}?start=${merchantCode}`;
    const statusLabel = data.is_active ? 'Open for orders' : 'Closed';
    const statusClasses = data.is_active
        ? 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-700/60 dark:bg-emerald-900/20 dark:text-emerald-300'
        : 'border-rose-200 bg-rose-50 text-rose-700 dark:border-rose-700/60 dark:bg-rose-900/20 dark:text-rose-300';

    const handleCopy = () => {
        navigator.clipboard.writeText(botLink);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleSave = (e: React.FormEvent) => {
        e.preventDefault();
        put(route('bots.telegram.update-merchant'), {
            preserveScroll: true,
        });
    };

    const handleServiceToggle = (serviceId: string, checked: boolean) => {
        if (checked) {
            setData('allowed_services', [...data.allowed_services, serviceId]);
        } else {
            setData('allowed_services', data.allowed_services.filter(id => id !== serviceId));
        }
    };

    return (
        <AppLayout breadcrumbs={[{ title: 'Telegram Sales Channel', href: route('bots.telegram.index') }]}>
            <Head title="Telegram Sales Channel" />

            <div className=" space-y-8 p-6 py-6">
                <div>
                    <h2 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-white">Telegram Sales Channel</h2>
                    <p className="mt-1 text-slate-500 dark:text-slate-300">
                        Allow your customers to buy VTU services directly from Telegram. Purchases will be credited to your business.
                    </p>
                </div>

                <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
                    {/* Shareable Link & Stats Column */}
                    <div className="space-y-6 md:col-span-1">
                        <Card className="overflow-hidden border-none bg-indigo-600 text-white shadow-xl shadow-indigo-500/10">
                            <CardHeader>
                                <CardTitle className="text-lg text-white">Your Bot Link</CardTitle>
                                <CardDescription className="text-indigo-200">
                                    Share this link on WhatsApp, Instagram, or your website to let customers order from Telegram.
                                </CardDescription>
                            </CardHeader>
                            <CardContent className="space-y-5">
                                <div className="rounded-3xl bg-indigo-900/20 p-4 text-sm leading-6 ring-1 ring-white/10">
                                    <p className="font-semibold text-white">Instant access for customers</p>
                                    <p className="mt-2 text-indigo-100/85">
                                        Use the Telegram deep link below or share the QR code so customers can start shopping immediately.
                                    </p>
                                </div>

                                <div className="grid gap-3">
                                    <div className="rounded-2xl border border-indigo-500/30 bg-indigo-900/30 p-4 text-sm text-indigo-100">
                                        <p className="font-medium text-indigo-100">Bot status</p>
                                        <p className="mt-1 text-base font-semibold">{statusLabel}</p>
                                    </div>
                                    <div className="flex flex-col gap-3">
                                        <Input
                                            readOnly
                                            value={botLink}
                                            className="border-indigo-400/70 bg-indigo-700/40 text-sm text-white focus-visible:ring-0"
                                        />
                                        <div className="flex flex-wrap items-center gap-2">
                                            <Button
                                                onClick={handleCopy}
                                                variant="secondary"
                                                className="min-w-[10rem] bg-white font-bold text-indigo-600 hover:bg-slate-100 dark:bg-slate-900 dark:text-indigo-300 dark:hover:bg-slate-800"
                                            >
                                                {copied ? 'Copied!' : 'Copy link'}
                                            </Button>
                                            <a
                                                href={botLink}
                                                target="_blank"
                                                rel="noreferrer"
                                                className="inline-flex items-center rounded-full border border-white/30 bg-white/10 px-4 py-2 text-sm font-semibold text-white transition hover:bg-white/15"
                                            >
                                                Open in Telegram
                                            </a>
                                        </div>
                                        <p className="text-xs text-indigo-200/90">
                                            Bot username: <span className="font-semibold">@{globalBotUsername}</span>
                                        </p>
                                    </div>
                                </div>
                            </CardContent>
                        </Card>

                        {/* Bot Performance / Sales Card */}
                        <Card className="overflow-hidden">
                            <CardHeader className="pb-3">
                                <CardTitle className="text-lg">Bot Performance</CardTitle>
                                <CardDescription>Sales generated via Telegram</CardDescription>
                            </CardHeader>
                            <CardContent className="grid gap-4 sm:grid-cols-3">
                                <div className={`rounded-3xl border p-4 ${statusClasses}`}>
                                    <p className="text-sm font-medium">Bot status</p>
                                    <p className="mt-2 text-2xl font-semibold tracking-tight">{statusLabel}</p>
                                </div>
                                <div className="rounded-3xl border border-slate-100 bg-slate-50/80 p-4 dark:border-slate-800/50 dark:bg-slate-900/15">
                                    <p className="text-sm font-medium text-slate-500 dark:text-slate-400">Total Revenue</p>
                                    <p className="mt-2 text-2xl font-bold tracking-tight text-slate-900 dark:text-white">
                                        ₦{totalSalesAmount.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                                    </p>
                                </div>
                                <div className="rounded-3xl border border-slate-100 bg-slate-50/80 p-4 dark:border-slate-800/50 dark:bg-slate-900/15">
                                    <p className="text-sm font-medium text-slate-500 dark:text-slate-400">Transactions Completed</p>
                                    <p className="mt-2 text-2xl font-bold tracking-tight text-slate-900 dark:text-white">
                                        {totalSalesCount.toLocaleString()}
                                    </p>
                                </div>
                            </CardContent>
                        </Card>
                    </div>

                    {/* Configuration Column */}
                    <div className="space-y-6 md:col-span-2">
                        <Card>
                            <CardHeader>
                                <CardTitle>Bot Preferences</CardTitle>
                                <CardDescription>Customize how the bot interacts with your customers.</CardDescription>
                            </CardHeader>
                            <div className="flex flex-wrap gap-3 border-b border-slate-200/80 bg-slate-50/70 px-6 py-4 dark:border-slate-800 dark:bg-slate-900/40">
                                <div className="rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-200">
                                    {enabledServicesCount} services active
                                </div>
                                <div className="rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-200">
                                    {data.welcome_message ? 'Welcome message ready' : 'No welcome message yet'}
                                </div>
                            </div>
                            <form onSubmit={handleSave}>
                                <CardContent className="space-y-8">
                                    {/* Enable/Disable Toggle */}
                                    <div className="flex items-center justify-between rounded-lg border border-slate-200 bg-slate-50/50 p-4 dark:border-slate-700 dark:bg-slate-900/50">
                                        <div className="space-y-0.5">
                                            <Label className="text-base font-semibold">Enable Telegram Bot</Label>
                                            <p className="text-sm text-slate-500">Allow customers to interact and make purchases.</p>
                                        </div>
                                        <Switch checked={data.is_active} onCheckedChange={(checked) => setData('is_active', checked)} />
                                    </div>

                                    {/* Allowed Services Toggles */}
                                    <div className="space-y-4 border-t border-slate-200 pt-6 dark:border-slate-800">
                                        <div>
                                            <Label className="text-base font-semibold">Services Offered</Label>
                                            <p className="mt-1 text-sm text-slate-500">
                                                Select which VTU services your bot is allowed to sell to customers.
                                            </p>
                                        </div>

                                        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                                            {AVAILABLE_SERVICES.map((service) => (
                                                <div
                                                    key={service.id}
                                                    className="flex items-center justify-between rounded-lg border border-slate-200 p-3 transition-colors hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800/50"
                                                >
                                                    <Label htmlFor={`service-${service.id}`} className="cursor-pointer text-sm font-medium">
                                                        {service.label}
                                                    </Label>
                                                    <Switch
                                                        id={`service-${service.id}`}
                                                        checked={data.allowed_services.includes(service.id)}
                                                        onCheckedChange={(checked) => handleServiceToggle(service.id, checked)}
                                                    />
                                                </div>
                                            ))}
                                        </div>
                                    </div>

                                    {/* Welcome Message */}
                                    <div className="space-y-3 border-t border-slate-200 pt-6 dark:border-slate-800">
                                        <Label htmlFor="welcome_message" className="text-base font-semibold">Custom Welcome Message</Label>
                                        <p className="text-sm text-slate-500 mb-2">
                                            This message is sent the very first time a customer clicks your bot link.
                                        </p>
                                        <Textarea
                                            id="welcome_message"
                                            placeholder="e.g., Welcome to my VTU store! How can I help you today?"
                                            className="min-h-[100px] resize-none"
                                            value={data.welcome_message}
                                            onChange={(e) => setData('welcome_message', e.target.value)}
                                        />
                                    </div>

                                    {!data.is_active && (
                                        <Alert variant="destructive" className="border-red-200 bg-red-50 text-red-800 dark:border-red-900/50 dark:bg-red-900/20 dark:text-red-300">
                                            <AlertTitle>Bot is disabled</AlertTitle>
                                            <AlertDescription>
                                                If a customer clicks your link right now, the bot will tell them your store is currently closed.
                                            </AlertDescription>
                                        </Alert>
                                    )}
                                </CardContent>
                                <CardFooter className="flex items-center justify-between border-t border-slate-200/70 bg-slate-50 px-6 py-4 dark:border-slate-800 dark:bg-slate-900">
                                    {recentlySuccessful ? (
                                        <span className="text-sm font-medium text-emerald-600">Preferences updated!</span>
                                    ) : (
                                        <span className="text-sm text-slate-500">Save changes to apply immediately.</span>
                                    )}
                                    <Button type="submit" disabled={processing}>
                                        {processing ? 'Saving...' : 'Save Preferences'}
                                    </Button>
                                </CardFooter>
                            </form>
                        </Card>
                    </div>
                </div>
            </div>
        </AppLayout>
    );
}
