import React from 'react';
import DocsLayout from '@/layouts/docs-layout';
import CodeBlock from '@/components/code-block';
import DocsParameters from '@/components/docs-parameters';
import { Badge } from '@/components/ui/badge';
import Callout from '@/components/docs-callout';

export default function AirtimeDocs() {
    return (
        <DocsLayout currentPath='/docs/airtime' title="Airtime Top-up">
            <div className="max-w-4xl">
                <h1 className="text-3xl font-bold text-white mb-4">Airtime Top-up</h1>
                <p className="text-slate-400 text-lg mb-8 leading-relaxed">
                    The Airtime API allows you to programmatically send airtime to any supported mobile network in Nigeria. 
                    Transactions are processed instantly and your wallet is debited upon a successful response.
                </p>

                <div className="flex items-center gap-4 bg-slate-900 border border-slate-800 rounded-lg p-4 mb-8">
                    <Badge className="bg-emerald-500/10 text-emerald-500 border-emerald-500/20 text-sm font-mono px-3">POST</Badge>
                    <code className="text-slate-300 font-mono text-sm break-all">
                        https://api.yourdomain.com/v1/airtime
                    </code>
                </div>

                <Callout type="info" title="Idempotency">
                    We recommend attaching a unique <code>tx_ref</code> to every request. If a transaction with the same reference is submitted twice within 5 minutes, we will return the original response rather than charging you again.
                </Callout>

                <h2 className="text-xl font-semibold text-white mt-10 mb-4 border-b border-slate-800 pb-2">Request Parameters</h2>
                
                <DocsParameters 
                    parameters={[
                        {
                            name: 'network',
                            type: 'string',
                            required: true,
                            description: (
                                <>
                                    <p>The network provider code.</p>
                                    <p className="mt-2">Supported values: <code className="text-xs bg-slate-800 px-1 py-0.5 rounded text-amber-300">mtn</code>, <code className="text-xs bg-slate-800 px-1 py-0.5 rounded text-green-400">glo</code>, <code className="text-xs bg-slate-800 px-1 py-0.5 rounded text-red-400">airtel</code>, <code className="text-xs bg-slate-800 px-1 py-0.5 rounded text-emerald-400">9mobile</code>.</p>
                                </>
                            )
                        },
                        {
                            name: 'plan_type',
                            type: 'string',
                            required: true,
                            description: 'The type of airtime to vend. For standard airtime, this is usually "VTU" or "Share and Sell".'
                        },
                        {
                            name: 'amount',
                            type: 'integer',
                            required: true,
                            description: 'The amount of airtime to send in Naira (NGN). Must be at least 1.'
                        },
                        {
                            name: 'phone',
                            type: 'string',
                            required: true,
                            description: 'The 11-digit Nigerian phone number to top up (e.g., 08012345678).'
                        },
                        {
                            name: 'tx_ref',
                            type: 'string',
                            required: true,
                            description: 'A unique reference ID generated by your system to track this specific transaction.'
                        },
                        {
                            name: 'bypass',
                            type: 'boolean',
                            required: false,
                            description: 'Set to true if the phone number has been ported to a different network to skip our internal prefix validation.'
                        }
                    ]}
                />

                <h2 className="text-xl font-semibold text-white mt-10 mb-4 border-b border-slate-800 pb-2">Example Request</h2>
                <div className="mb-8">
                    {/* Assuming CodeBlock supports tabs, or just default to cURL/PHP */}
                    <CodeBlock 
                        language="bash"
                        title="cURL"
                        code={`curl -X POST https://api.yourdomain.com/v1/airtime \\
  -H "Authorization: Bearer sk_live_your_api_key_here" \\
  -H "Content-Type: application/json" \\
  -H "Accept: application/json" \\
  -d '{
    "network": "mtn",
    "plan_type": "VTU",
    "amount": 500,
    "phone": "08012345678",
    "tx_ref": "tx-1234567890"
  }'`}
                    />
                </div>

                <h2 className="text-xl font-semibold text-white mt-10 mb-4 border-b border-slate-800 pb-2">Response Handling</h2>
                <p className="text-slate-400 mb-4 leading-relaxed">
                    A successful request will return a <code>200 OK</code> status code.
                </p>

                <CodeBlock 
                    language="json"
                    title="Success Response (200)"
                    code={`{
  "status": true,
  "message": "Airtime purchase successful",
  "data": {
    "reference": "tx-1234567890",
    "network": "mtn",
    "amount": 500,
    "phone": "08012345678",
    "status": "successful",
    "balance_before": "5000.00",
    "balance_after": "4500.00",
    "created_at": "2026-04-17T10:00:00Z"
  }
}`}
                />

                <div className="mt-8">
                     <CodeBlock 
                        language="json"
                        title="Validation Error (422)"
                        code={`{
  "status": false,
  "message": "Validation failed. Please check the provided data.",
  "errors": {
    "phone": [
      "The phone number 08012345678 does not appear to be a valid MTN number. If this is a ported number, please use the bypass option."
    ]
  }
}`}
                    />
                </div>
            </div>
        </DocsLayout>
    );
}