// resources/js/pages/docs/cable.tsx

import CodeBlock from '@/components/code-block';
import DocsCallout from '@/components/docs-callout';
import DocsParameters from '@/components/docs-parameters';
import { Badge } from '@/components/ui/badge';
import DocsLayout from '@/layouts/docs-layout';
import { Head } from '@inertiajs/react';

export default function CableDocumentation() {
    return (
        <DocsLayout currentPath="/docs/cable" title='Cable'>
            <Head title="Cable TV Subscriptions - API Documentation" />

            <div>
                <h1 className="mb-2 text-3xl font-bold tracking-tight">Cable TV Subscriptions</h1>
                <p className="mb-6 text-lg text-slate-600 dark:text-slate-400">
                    Use this endpoint to process cable TV subscriptions like DSTV, GOTV, and Startimes.
                </p>
                <DocsCallout title="IUC Verification Recommended" type="info">
                    It is highly recommended to verify the customer's IUC/Smartcard number before initiating a purchase to prevent failed transactions
                    due to invalid accounts.
                </DocsCallout>
            </div>

            <div className="mt-12 border-t pt-10">
                <h2 className="mb-4 text-2xl font-bold tracking-tight" id="purchase-cable">
                    Purchase Cable Subscription
                </h2>

                <div className="mb-6 flex items-center gap-3">
                    <Badge variant="default" className="bg-emerald-500 text-white hover:bg-emerald-600">
                        POST
                    </Badge>
                    <code className="bg-muted rounded px-2 py-1 font-mono text-sm">/api/v1/cable</code>
                </div>

                <div className="grid grid-cols-1 items-start gap-8 lg:grid-cols-2">
                    <div>
                        <h3 className="mb-4 text-lg font-semibold">Request Parameters</h3>
                        <DocsParameters
                            parameters={[
                                { name: 'cable', type: 'string', required: true, description: 'The cable provider. e.g., DSTV, GOTV, STARTIMES.' },
                                {
                                    name: 'cable_plan',
                                    type: 'string/integer',
                                    required: true,
                                    description: 'The unique ID or code of the cable plan you are subscribing to.',
                                },
                                { name: 'iuc', type: 'string', required: true, description: 'The smartcard number or IUC number of the decoder.' },
                                {
                                    name: 'request-id',
                                    type: 'string',
                                    required: true,
                                    description: 'A unique transaction reference (max 50 chars) generated by your application.',
                                },
                                {
                                    name: 'bypass',
                                    type: 'boolean',
                                    required: false,
                                    description: 'Set to true to bypass duplicate transaction checks (not recommended).',
                                },
                            ]}
                        />
                    </div>

                    <div className="space-y-6">
                        <div>
                            <h3 className="mb-2 text-sm font-medium">Example Request</h3>
                            <CodeBlock
                                language="json"
                                code={`{
  "cable": "DSTV",
  "cable_plan": "dstv-padi",
  "iuc": "1234567890",
  "request-id": "CABLE_TX_99018283"
}`}
                            />
                        </div>
                        <div>
                            <h3 className="mb-2 text-sm font-medium">Example Response (Success)</h3>
                            <CodeBlock
                                language="json"
                                code={`{
  "status": "success",
  "message": "Cable subscription successful.",
  "data": {
    "transaction_reference": "CABLE_TX_99018283",
    "provider": "DSTV",
    "amount": 2500,
    "status": "successful"
  }
}`}
                            />
                        </div>
                    </div>
                </div>
            </div>
        </DocsLayout>
    );
}
