import React from 'react';
import DocsLayout from '@/layouts/docs-layout';
import CodeBlock from '@/components/code-block';
import DocsParameters from '@/components/docs-parameters';
import { Badge } from '@/components/ui/badge';
import Callout from '@/components/docs-callout';

export default function DataDocs() {
    return (
        <DocsLayout currentPath='/docs/data' title="Data Top-up">
            <div className="max-w-4xl">
                <h1 className="text-3xl font-bold text-white mb-4">Data Top-up</h1>
                <p className="text-slate-400 text-lg mb-8 leading-relaxed">
                    The Data API allows you to vend internet data bundles to any supported mobile network.
                    Transactions are processed instantly, and your wallet is debited based on the specific plan's pricing.
                </p>

                <div className="flex items-center gap-4 bg-slate-900 border border-slate-800 rounded-lg p-4 mb-8">
                    <Badge className="bg-emerald-500/10 text-emerald-500 border-emerald-500/20 text-sm font-mono px-3">POST</Badge>
                    <code className="text-slate-300 font-mono text-sm break-all">
                        https://api.yourdomain.com/v1/data
                    </code>
                </div>

                <Callout type="warning" title="Fetching Data Plans">
                    Before making a purchase request, you must fetch the available data plans using the <code className="text-amber-300 bg-slate-900 px-1 py-0.5 rounded">GET /v1/data/plans</code> endpoint. The purchase payload requires the specific integer <code>data_plan</code> ID returned by that endpoint.
                </Callout>

                <h2 className="text-xl font-semibold text-white mt-10 mb-4 border-b border-slate-800 pb-2">Request Parameters</h2>

                <DocsParameters
                    parameters={[
                        {
                            name: 'network',
                            type: 'string',
                            required: true,
                            description: (
                                <>
                                    <p>The network provider code.</p>
                                    <p className="mt-2">Supported values: <code className="text-xs bg-slate-800 px-1 py-0.5 rounded text-amber-300">mtn</code>, <code className="text-xs bg-slate-800 px-1 py-0.5 rounded text-green-400">glo</code>, <code className="text-xs bg-slate-800 px-1 py-0.5 rounded text-red-400">airtel</code>, <code className="text-xs bg-slate-800 px-1 py-0.5 rounded text-emerald-400">9mobile</code>.</p>
                                </>
                            )
                        },
                        {
                            name: 'data_plan',
                            type: 'integer',
                            required: true,
                            description: 'The unique ID of the data bundle you wish to purchase (e.g., 25 for MTN 1GB 30Days).'
                        },
                        {
                            name: 'phone',
                            type: 'string',
                            required: true,
                            description: 'The 11-digit Nigerian phone number to receive the data bundle (e.g., 08012345678).'
                        },
                        {
                            name: 'tx_ref',
                            type: 'string',
                            required: true,
                            description: 'A unique reference ID generated by your system to track this specific transaction. Used for idempotency.'
                        }
                    ]}
                />

                <h2 className="text-xl font-semibold text-white mt-10 mb-4 border-b border-slate-800 pb-2">Example Request</h2>
                <div className="mb-8">
                    <CodeBlock
                        language="bash"
                        title="cURL"
                        code={`curl -X POST https://api.yourdomain.com/v1/data \\
  -H "Authorization: Bearer sk_live_your_api_key_here" \\
  -H "Content-Type: application/json" \\
  -H "Accept: application/json" \\
  -d '{
    "network": "mtn",
    "data_plan": 25,
    "phone": "08012345678",
    "tx_ref": "data-tx-987654321"
  }'`}
                    />
                </div>

                <h2 className="text-xl font-semibold text-white mt-10 mb-4 border-b border-slate-800 pb-2">Response Handling</h2>
                <p className="text-slate-400 mb-4 leading-relaxed">
                    A successful request will return a <code>200 OK</code> status code.
                </p>

                <CodeBlock
                    language="json"
                    title="Success Response (200)"
                    code={`{
  "status": true,
  "message": "Data purchase successful",
  "data": {
    "reference": "data-tx-987654321",
    "network": "mtn",
    "plan_name": "MTN 1GB (30 Days)",
    "amount": 250,
    "phone": "08012345678",
    "status": "successful",
    "balance_before": "4500.00",
    "balance_after": "4250.00",
    "created_at": "2026-04-18T14:30:00Z"
  }
}`}
                />

                <div className="mt-8">
                     <CodeBlock
                        language="json"
                        title="Validation Error (422) - Invalid Plan"
                        code={`{
  "status": false,
  "message": "Validation failed. Please check the provided data.",
  "errors": {
    "data_plan": [
      "The selected data plan is invalid or not available for the MTN network."
    ]
  }
}`}
                    />
                </div>
            </div>
        </DocsLayout>
    );
}
