// resources/js/pages/docs/pins.tsx

import CodeBlock from '@/components/code-block';
import DocsCallout from '@/components/docs-callout';
import DocsParameters from '@/components/docs-parameters';
import { Badge } from '@/components/ui/badge';
import DocsLayout from '@/layouts/docs-layout';
import { Head } from '@inertiajs/react';

export default function PinsDocumentation() {
    return (
        <DocsLayout currentPath='/docs/pins' title='Pins'>
            <Head title="Generate PINs & Vouchers - API Documentation" />

            <div>
                <h1 className="mb-2 text-3xl font-bold tracking-tight">Generate PINs & Vouchers</h1>
                <p className="mb-6 text-lg text-slate-600 dark:text-slate-400">
                    Learn how to generate reusable Airtime and Data Vouchers (PINs) through the API.
                </p>
                <DocsCallout title="Overview" type="info">
                    Unlike standard direct top-ups (VTU), PIN generation does not require a target phone number. Instead, it securely locks inventory, deducts your wallet, and returns the raw PINs which you can dispense or print for your users.
                </DocsCallout>
            </div>

            {/* AIRTIME PIN SECTION */}
            <div className="mt-12 border-t pt-10">
                <h2 className="mb-4 text-2xl font-bold tracking-tight" id="airtime-pin">
                    Generate Airtime PINs
                </h2>

                <div className="mb-6 flex items-center gap-3">
                    <Badge variant="default" className="bg-emerald-500 text-white hover:bg-emerald-600">POST</Badge>
                    <code className="rounded bg-muted px-2 py-1 font-mono text-sm">/api/v1/airtime-pin</code>
                </div>

                <div className="grid grid-cols-1 items-start gap-8 lg:grid-cols-2">
                    <div>
                        <h3 className="mb-4 text-lg font-semibold">Request Parameters</h3>
                        <DocsParameters
                            parameters={[
                                { name: 'network', type: 'string', required: true, description: 'The network provider. e.g., MTN, GLO, AIRTEL, 9MOBILE.' },
                                { name: 'amount', type: 'numeric', required: true, description: 'The denomination of the PIN you wish to generate (e.g., 100, 200, 500).' },
                                { name: 'quantity', type: 'integer', required: false, description: 'The number of PINs to generate in a single batch. Minimum: 1, Maximum: 50. Defaults to 1.' },
                                { name: 'tx_ref', type: 'string', required: true, description: 'A unique transaction reference generated by your system to prevent duplicate billing.' },
                            ]}
                        />

                        <div className="mt-6">
                            <DocsCallout title="Concurrency Safe" type="info">
                                The API safely locks inventory rows during generation. If you request 5 PINs, the system ensures those exact 5 PINs cannot be dispensed to another concurrent request.
                            </DocsCallout>
                        </div>
                    </div>

                    <div className="space-y-6">
                        <div>
                            <h3 className="mb-2 text-sm font-medium">Example Request</h3>
                            <CodeBlock
                                language="json"
                                code={`{
  "network": "MTN",
  "amount": 100,
  "quantity": 3,
  "tx_ref": "PIN_1234567890"
}`}
                            />
                        </div>
                        <div>
                            <h3 className="mb-2 text-sm font-medium">Example Response (Success)</h3>
                            <CodeBlock
                                language="json"
                                code={`{
  "status": "success",
  "message": "3 PIN(s) generated successfully.",
  "data": {
    "pins": [
      "123456789012345",
      "987654321098765",
      "112233445566778"
    ]
  }
}`}
                            />
                        </div>
                    </div>
                </div>
            </div>

            {/* DATA PIN SECTION */}
            <div className="mt-16 border-t pt-10">
                <h2 className="mb-4 text-2xl font-bold tracking-tight" id="data-pin">
                    Generate Data PINs
                </h2>
                <p className="mb-6 text-slate-600 dark:text-slate-400">
                    Unlike Airtime PINs which are matched by amount, Data PINs are matched by the exact data plan <code>name</code> (e.g., "MTN 1.5GB"). The API will automatically determine the cost.
                </p>

                <div className="mb-6 flex items-center gap-3">
                    <Badge variant="default" className="bg-emerald-500 text-white hover:bg-emerald-600">POST</Badge>
                    <code className="rounded bg-muted px-2 py-1 font-mono text-sm">/api/v1/data-pin</code>
                </div>

                <div className="grid grid-cols-1 items-start gap-8 lg:grid-cols-2">
                    <div>
                        <h3 className="mb-4 text-lg font-semibold">Request Parameters</h3>
                        <DocsParameters
                            parameters={[
                                { name: 'network', type: 'string', required: true, description: 'The network provider. e.g., MTN, GLO.' },
                                { name: 'name', type: 'string', required: true, description: 'The exact name/volume of the Data PIN plan as configured on the platform (e.g. "MTN 1.5GB").' },
                                { name: 'quantity', type: 'integer', required: false, description: 'Number of PINs to generate (Max: 50). Defaults to 1.' },
                                { name: 'tx_ref', type: 'string', required: true, description: 'A unique reference to identify this transaction.' },
                            ]}
                        />

                        <div className="mt-6">
                            <DocsCallout title="Data Plan Names" type="warning">
                                Ensure the <code className="text-xs">name</code> parameter matches the exact naming convention provided by the platform. Any mismatch will result in a 404 error.
                            </DocsCallout>
                        </div>
                    </div>

                    <div className="space-y-6">
                        <div>
                            <h3 className="mb-2 text-sm font-medium">Example Request</h3>
                            <CodeBlock
                                language="json"
                                code={`{
  "network": "MTN",
  "name": "MTN 1.5GB",
  "quantity": 2,
  "tx_ref": "DPIN_99887766"
}`}
                            />
                        </div>
                        <div>
                            <h3 className="mb-2 text-sm font-medium">Example Response</h3>
                            <CodeBlock
                                language="json"
                                code={`{
  "status": "success",
  "message": "2 PIN(s) generated successfully.",
  "data": {
    "pins": [
      "555544443333222",
      "777788889999000"
    ]
  }
}`}
                            />
                        </div>
                    </div>
                </div>
            </div>
        </DocsLayout>
    );
}
